development:
  domain: sahara.org
  project_name: SaharaRights
  contact_email: deal@sindominio.net

test:
  domain: sahara.org
  project_name: SaharaRights
  contact_email: deal@sindominio.net

production:
  domain: sahararights.net
  project_name: SaharaRights
  contact_email: deal@sindominio.net

